language: go
sudo: true

go:
  - 1.2
  - 1.3
  - 1.4
  - 1.5
  - tip

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get install -y libusb-dev

script:
  - go test -v github.com/fgrosse/blink
