language: go
sudo: false

go:
  - 1.2
  - 1.3
  - 1.4
  - 1.5
  - tip

addons:
  apt:
    packages:
    - libusb-1.0-0-dev

install:
  - go get github.com/stretchr/testify/...

script:
  - go test -v github.com/fgrosse/blink
